@startuml
'https://plantuml.com/sequence-diagram

class Main {
    + main(String[]): void
    - stringInput(): String
    - numberInput(): int
    - numberInput(int, int): int
    - menuChoice(int): int
    - menu(): void
    - run(String[]): void
}

class Facade {
    + SpoolManager
    + PrintManager
    + PrinterManager
    - showPrinters(): void
    - showSpools(): void
    - showPrints(): void
    - showPendingPrintTasks(): void
    - startPrintQueue(): void
    - addNewPrintTask(): void
    - registerPrinterFailure(): void
    - registerPrintCompletion(): void
    - changePrintStrategy(): void
    - exit(): void
}

class PrintManager {
    + PrintManager()
    + addPrintTask(String, List<String>, FilamentType): void
    + findPrint(String): Print
    + addPrint(String, int, int, int, ArrayList<Double>, int): void
    - readPrintsFromFile(String): void
    + prints: List<Print>
}

class SpoolManager {
    + SpoolManager()
    + addSpool(Spool): void
    + getSpoolByID(int): Spool
    - readSpoolsFromFile(String): void
    + spools: List<Spool>
}

class PrinterManager {
    + PrinterManager()
    + addPrinter(int, int, String, String, int, int, int, int): void
    + findPrinter(int): Printer
    + getPrinterCurrentTask(Printer): PrintTask
    + getPendingPrintTasks: List<PrintTask>
    + getPrinters: List<Printer
    + selectPrintTask(Printer): void
    + registerCompletion(int): void
    + registerPrinterFailure(int): void
    + startInitialQueue(): void
    - printError(String): void
    - readPrintersFromFile(String): void
    - Map<Printer, ArrayList<PrintTask>> printers
}



Main -down-> Facade
Facade -down-> SpoolManager
Facade -down-> PrintManager
Facade -down-> PrinterManager

@enduml